# Generated by Django 4.2.6 on 2023-12-16 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_ph_employee_iks_ph_employee_ifs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Canal_p',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.basereport')),
            ],
            bases=('reports.basereport',),
        ),
        migrations.CreateModel(
            name='Eleven',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.basereport')),
            ],
            bases=('reports.basereport',),
        ),
        migrations.CreateModel(
            name='FTTH',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.basereport')),
            ],
            bases=('reports.basereport',),
        ),
        migrations.CreateModel(
            name='FTTH_B',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.basereport')),
            ],
            bases=('reports.basereport',),
        ),
        migrations.CreateModel(
            name='Home_points',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.basereport')),
            ],
            bases=('reports.basereport',),
        ),
        migrations.CreateModel(
            name='LTE',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.basereport')),
            ],
            bases=('reports.basereport',),
        ),
        migrations.CreateModel(
            name='LTE_B',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.basereport')),
            ],
            bases=('reports.basereport',),
        ),
        migrations.CreateModel(
            name='MO',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.basereport')),
            ],
            bases=('reports.basereport',),
        ),
        migrations.CreateModel(
            name='MV_TO_FBB',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.basereport')),
            ],
            bases=('reports.basereport',),
        ),
        migrations.CreateModel(
            name='MV_TO_FBB_B',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.basereport')),
            ],
            bases=('reports.basereport',),
        ),
        migrations.CreateModel(
            name='Netflix',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.basereport')),
            ],
            bases=('reports.basereport',),
        ),
        migrations.CreateModel(
            name='OL_Extra',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.basereport')),
            ],
            bases=('reports.basereport',),
        ),
        migrations.CreateModel(
            name='OL_F',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.basereport')),
            ],
            bases=('reports.basereport',),
        ),
        migrations.CreateModel(
            name='OL_Mini',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.basereport')),
            ],
            bases=('reports.basereport',),
        ),
        migrations.CreateModel(
            name='OL_Standard',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.basereport')),
            ],
            bases=('reports.basereport',),
        ),
        migrations.CreateModel(
            name='OSP',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.basereport')),
            ],
            bases=('reports.basereport',),
        ),
        migrations.CreateModel(
            name='OSPX2',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.basereport')),
            ],
            bases=('reports.basereport',),
        ),
        migrations.CreateModel(
            name='PB',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.basereport')),
            ],
            bases=('reports.basereport',),
        ),
        migrations.CreateModel(
            name='Plan_FL',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.basereport')),
            ],
            bases=('reports.basereport',),
        ),
        migrations.CreateModel(
            name='Plan_FM',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.basereport')),
            ],
            bases=('reports.basereport',),
        ),
        migrations.CreateModel(
            name='Plan_FS',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.basereport')),
            ],
            bases=('reports.basereport',),
        ),
        migrations.CreateModel(
            name='Plan_FXL',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.basereport')),
            ],
            bases=('reports.basereport',),
        ),
        migrations.CreateModel(
            name='Plan_L',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.basereport')),
            ],
            bases=('reports.basereport',),
        ),
        migrations.CreateModel(
            name='Plan_M',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.basereport')),
            ],
            bases=('reports.basereport',),
        ),
        migrations.CreateModel(
            name='Plan_S',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.basereport')),
            ],
            bases=('reports.basereport',),
        ),
        migrations.CreateModel(
            name='Retention',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.basereport')),
            ],
            bases=('reports.basereport',),
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.basereport')),
            ],
            bases=('reports.basereport',),
        ),
        migrations.CreateModel(
            name='XDSL',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.basereport')),
            ],
            bases=('reports.basereport',),
        ),
        migrations.CreateModel(
            name='XDSL_B',
            fields=[
                ('basereport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.basereport')),
            ],
            bases=('reports.basereport',),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=20, unique=True)),
                ('ph_employee_id', models.CharField(blank=True, null=True)),
                ('ph_employee_ifs', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('ph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ph')),
            ],
        ),
        migrations.AddField(
            model_name='basereport',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report'),
        ),
    ]
